# Generated by Django 5.1.1 on 2024-12-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='naam',
            field=models.CharField(default='no_name', max_length=100, null=True),
        ),
    ]
