# Generated by Django 5.1.1 on 2024-12-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_user_naam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='naam',
        ),
    ]
