# Generated by Django 5.1.1 on 2024-12-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_user_naam'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='naam',
            field=models.CharField(default='No_Name', max_length=10, null=True),
        ),
    ]
