# Generated by Django 5.1.3 on 2025-01-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_user_naam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='total_amount',
        ),
    ]
