# Generated by Django 5.1.3 on 2025-01-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_expense_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
    ]
